import { getUser } from "@/auth/user";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUser();
  if (!user) return;

  if (!user.super_admin && !user.role?.permissions?.users?.includes("read")) {
    return null;
  }
  return <div>{children}</div>;
}
