import type { Metadata } from "next";
import TrashesSidebar from "./components/sidebar";

export const metadata: Metadata = {
  title: "Trashes",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full h-full flex">
      <TrashesSidebar />
      <div className="flex-1 h-full">{children}</div>
    </div>
  );
}
