import type { Metadata } from "next";
import "./globals.css";
import Currency from "@/models/currency";
import Bill from "@/models/bill";
import sequelize from "@/lib/mysql";
import EventTracking from "@/models/events";
import Device from "@/models/devices";
import Role from "@/models/role";
import User from "@/models/user";
import Plan from "@/models/plan";
import Status from "@/models/statuses";
import { seed } from "@/database/seed";
import Branch from "@/models/branch";
import BranchDetail from "./(dashboard)/workflows/branches/[id]/page";
import BranchDevice from "@/models/branch_device";

export const metadata: Metadata = {
  title: "Starlink",
  description: "Generated by create next app",
  icons: { icon: "/logo.png" },
};

const update = async () => {
  await Bill.update({ status_id: "553905483434392" }, { where: {} });
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // User.sync({ alter: true })
  //   .then(() => console.log("synced", new Date()))
  //   .catch((error) => console.log("sync error", error));

  return (
    <html lang="en">
      <body className="h-screen w-screen">{children}</body>
    </html>
  );
}
