import type { Metadata } from "next";
import "./globals.css";
import DeviceEmail from "@/models/device_email";
import Bill from "@/models/bill";
import EventTracking from "@/models/events";

export const metadata: Metadata = {
  title: "Starlink",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  Bill.sync({ alter: true })
    .then(() => console.log("synced", new Date()))
    .catch((error) => console.log("sync error", error));

  return (
    <html lang="en">
      <body className="h-screen w-screen">{children}</body>
    </html>
  );
}
