import { Metadata } from "next";
import RoleClient from "./client";

export const metadata: Metadata = {
  title: "Resignations",
  description: "Generated by create next app",
  icons: { icon: "/vite.svg" },
};

async function Roles() {
  return <RoleClient />;
}

export default Roles;
