import { Metadata } from "next";
import "../globals.css";
import { redirect } from "next/navigation";
import { getUser } from "@/auth/user";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  if (user) redirect("/home");
  return <>{children}</>;
}
