import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Image
        src={"/home_b_hero_d.webp"}
        fill
        alt="background"
        className="object-cover"
      />
      {children}
    </>
  );
}
