import { getUser } from "@/auth/user";
import { DynamicBreadcrumb } from "@/components/dynamic-breadcrumb";
import { Separator } from "@/components/ui/separator";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { CustomQueryClientProvider } from "../contexts/tanstack";
import { HasUserProvider } from "../contexts/user";
import { VisitorProvider } from "../contexts/visitor";
import "../globals.css";
import Login from "../login/page";
import { AppSidebar } from "./components/sidebar/app-sidebar";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
  icons: { icon: "/logo.png" },
};

export default async function RootLayout({
  children,
  create,
}: Readonly<{
  children: React.ReactNode;
  create?: React.ReactNode;
}>) {
  const user = await getUser();
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang="en">
      <body className={`antialiased`} cz-shortcut-listen="true">
        <VisitorProvider>
          {user ? (
            <CustomQueryClientProvider>
              <HasUserProvider user={JSON.stringify(user)}>
                <SidebarProvider defaultOpen={defaultOpen}>
                  <main className="flex w-screen h-screen">
                    <AppSidebar />
                    <SidebarInset className="h-full overflow-y-auto">
                      <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
                        <div className="flex items-center gap-2 px-4">
                          <SidebarTrigger className="-ml-1" />
                          <Separator
                            orientation="vertical"
                            className="mr-2 h-4"
                          />
                          <DynamicBreadcrumb />
                        </div>
                      </header>
                      <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
                        {children}
                      </div>
                    </SidebarInset>
                  </main>
                </SidebarProvider>
              </HasUserProvider>
            </CustomQueryClientProvider>
          ) : (
            <Login />
          )}
        </VisitorProvider>
      </body>
    </html>
  );
}
