import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import Sidebar from "./_components/sidebar/sidebar";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default async function RootLayout({
  children,
  create,
}: Readonly<{
  children: React.ReactNode;
  create?: React.ReactNode;
}>) {
  return (
    <div className="w-full h-full">
      {create}
      <Sidebar />
      <div className="h-[calc(100%-56px)]">{children}</div>
      <Toaster />
    </div>
  );
}
